services:
  - name: icecast-server
    type: web
    env: docker
    repo: https://github.com/doctorxlovexat/icecast2  # Zameni sa tvojim repo URL
    branch: main  # Promeni ako koristiš drugi branch
    plan: free  # Možeš promeniti na "starter" ili "pro"
    envVars:
      - key: ICECAST_SOURCE_PASSWORD
        value: zizu
      - key: ICECAST_RELAY_PASSWORD
        value: zizu
      - key: ICECAST_ADMIN_PASSWORD
        value: zizu
      - key: ICECAST_ADMIN_USERNAME
        value: gladijator
    disk:
      name: icecast-logs
      mountPath: /var/log/icecast2/log
      sizeGB: 1
    healthCheckPath: /status.xsl
    autoDeploy: true
    buildCommand: "docker build -t icecast-server ."
    startCommand: "docker run -p 8080:8080 icecast-server"
